name: doctor
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6

  flutter:
    sdk: flutter

  # Splash Screen
  flutter_native_splash: ^2.4.0
  # For a responsive UI
  flutter_screenutil: ^5.9.1
  # An SVG rendering and widget library for Flutter, which allows painting 
  flutter_svg: ^2.0.10+1
  # State Management
  flutter_bloc: ^8.1.5
  # Code Generator for (cubit and retrofit)
  freezed: any
  freezed_annotation: ^2.4.1
  # for dependency injection
  get_it: ^7.7.0
  # Code Generator for converting to and from JSON by `annotation`
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  # Networking
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  pretty_dio_logger: ^1.3.1
  # Localization
  intl: ^0.19.0
  easy_localization: any
  # Data Persistence
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
